version: '3.9'

networks:
  app-networks:
    driver: bridge

volumes:
  postgres-data:
    driver: local

services:
  db:
    image: postgres:17.2-alpine
    container_name: postgres_weather_app
    hostname: postgres
    networks:
      - app-networks
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT_MAPPING}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE}'"]
      interval: 30s
      timeout: 10s
      retries: 5