name: maven-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build and Test
        run: mvn clean install

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: weather_app
          path: target/*.jar
