name: maven-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      # 3. Run Checkstyle to enforce code style
      - name: Check code style with Checkstyle
        run: mvn checkstyle:check

      # 4. Run tests
      - name: Test
        run: mvn test